
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMES\n    input : expr\n          | empty\n    \n    expr : expr PLUS term\n         | expr MINUS term\n         | term\n    \n    term : term TIMES factor\n         | term DIVIDE factor\n         | factor\n    \n    factor : LPAREN expr RPAREN\n           | NUMBER\n    empty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,7,13,14,15,16,17,],[-11,0,-1,-2,-5,-8,-10,-3,-4,-6,-7,-9,]),'LPAREN':([0,6,8,9,10,11,],[6,6,6,6,6,6,]),'NUMBER':([0,6,8,9,10,11,],[7,7,7,7,7,7,]),'PLUS':([2,4,5,7,12,13,14,15,16,17,],[8,-5,-8,-10,8,-3,-4,-6,-7,-9,]),'MINUS':([2,4,5,7,12,13,14,15,16,17,],[9,-5,-8,-10,9,-3,-4,-6,-7,-9,]),'RPAREN':([4,5,7,12,13,14,15,16,17,],[-5,-8,-10,17,-3,-4,-6,-7,-9,]),'TIMES':([4,5,7,13,14,15,16,17,],[10,-8,-10,10,10,-6,-7,-9,]),'DIVIDE':([4,5,7,13,14,15,16,17,],[11,-8,-10,11,11,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'expr':([0,6,],[2,12,]),'empty':([0,],[3,]),'term':([0,6,8,9,],[4,4,13,14,]),'factor':([0,6,8,9,10,11,],[5,5,5,5,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> expr','input',1,'p_input','validar.py',30),
  ('input -> empty','input',1,'p_input','validar.py',31),
  ('expr -> expr PLUS term','expr',3,'p_expr','validar.py',38),
  ('expr -> expr MINUS term','expr',3,'p_expr','validar.py',39),
  ('expr -> term','expr',1,'p_expr','validar.py',40),
  ('term -> term TIMES factor','term',3,'p_term','validar.py',46),
  ('term -> term DIVIDE factor','term',3,'p_term','validar.py',47),
  ('term -> factor','term',1,'p_term','validar.py',48),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor','validar.py',54),
  ('factor -> NUMBER','factor',1,'p_factor','validar.py',55),
  ('empty -> <empty>','empty',0,'p_empty','validar.py',63),
]
