
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND BOOLEAN LPAREN NOT OR RPAREN\n    input : logical_expr\n          | empty\n    \n    logical_expr : logical_expr AND logical_term\n                | logical_expr OR logical_term\n                | logical_term\n    \n    logical_term : NOT logical_factor\n                | logical_factor\n    \n    logical_factor : LPAREN logical_expr RPAREN\n                  | BOOLEAN\n    empty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,6,8,11,13,14,15,],[-10,0,-1,-2,-5,-7,-9,-6,-3,-4,-8,]),'NOT':([0,7,9,10,],[5,5,5,5,]),'LPAREN':([0,5,7,9,10,],[7,7,7,7,7,]),'BOOLEAN':([0,5,7,9,10,],[8,8,8,8,8,]),'AND':([2,4,6,8,11,12,13,14,15,],[9,-5,-7,-9,-6,9,-3,-4,-8,]),'OR':([2,4,6,8,11,12,13,14,15,],[10,-5,-7,-9,-6,10,-3,-4,-8,]),'RPAREN':([4,6,8,11,12,13,14,15,],[-5,-7,-9,-6,15,-3,-4,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'logical_expr':([0,7,],[2,12,]),'empty':([0,],[3,]),'logical_term':([0,7,9,10,],[4,4,13,14,]),'logical_factor':([0,5,7,9,10,],[6,11,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> logical_expr','input',1,'p_input','validar.py',27),
  ('input -> empty','input',1,'p_input','validar.py',28),
  ('logical_expr -> logical_expr AND logical_term','logical_expr',3,'p_logical_expr','validar.py',35),
  ('logical_expr -> logical_expr OR logical_term','logical_expr',3,'p_logical_expr','validar.py',36),
  ('logical_expr -> logical_term','logical_expr',1,'p_logical_expr','validar.py',37),
  ('logical_term -> NOT logical_factor','logical_term',2,'p_logical_term','validar.py',43),
  ('logical_term -> logical_factor','logical_term',1,'p_logical_term','validar.py',44),
  ('logical_factor -> LPAREN logical_expr RPAREN','logical_factor',3,'p_logical_factor','validar.py',50),
  ('logical_factor -> BOOLEAN','logical_factor',1,'p_logical_factor','validar.py',51),
  ('empty -> <empty>','empty',0,'p_empty','validar.py',59),
]
