
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftPLUSMINUSleftTIMESDIVIDErightNOTAND BOOLEAN DIVIDE LPAREN MINUS NOT NUMBER OR PLUS RPAREN TIMES\n    expression : expression PLUS term\n              | expression MINUS term\n              | expression AND term\n              | expression OR term\n              | term\n    \n    term : term TIMES factor\n         | term DIVIDE factor\n         | NOT factor\n         | factor\n    \n    factor : NUMBER\n           | BOOLEAN\n           | LPAREN expression RPAREN\n    '
    
_lr_action_items = {'NOT':([0,7,8,9,10,11,],[4,4,4,4,4,4,]),'NUMBER':([0,4,7,8,9,10,11,12,13,],[5,5,5,5,5,5,5,5,5,]),'BOOLEAN':([0,4,7,8,9,10,11,12,13,],[6,6,6,6,6,6,6,6,6,]),'LPAREN':([0,4,7,8,9,10,11,12,13,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,5,6,14,16,17,18,19,20,21,22,],[0,-5,-9,-10,-11,-8,-1,-2,-3,-4,-6,-7,-12,]),'PLUS':([1,2,3,5,6,14,15,16,17,18,19,20,21,22,],[8,-5,-9,-10,-11,-8,8,-1,-2,-3,-4,-6,-7,-12,]),'MINUS':([1,2,3,5,6,14,15,16,17,18,19,20,21,22,],[9,-5,-9,-10,-11,-8,9,-1,-2,-3,-4,-6,-7,-12,]),'AND':([1,2,3,5,6,14,15,16,17,18,19,20,21,22,],[10,-5,-9,-10,-11,-8,10,-1,-2,-3,-4,-6,-7,-12,]),'OR':([1,2,3,5,6,14,15,16,17,18,19,20,21,22,],[11,-5,-9,-10,-11,-8,11,-1,-2,-3,-4,-6,-7,-12,]),'RPAREN':([2,3,5,6,14,15,16,17,18,19,20,21,22,],[-5,-9,-10,-11,-8,22,-1,-2,-3,-4,-6,-7,-12,]),'TIMES':([2,3,5,6,14,16,17,18,19,20,21,22,],[12,-9,-10,-11,-8,12,12,12,12,-6,-7,-12,]),'DIVIDE':([2,3,5,6,14,16,17,18,19,20,21,22,],[13,-9,-10,-11,-8,13,13,13,13,-6,-7,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,],[1,15,]),'term':([0,7,8,9,10,11,],[2,2,16,17,18,19,]),'factor':([0,4,7,8,9,10,11,12,13,],[3,14,3,3,3,3,3,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression','validar.py',45),
  ('expression -> expression MINUS term','expression',3,'p_expression','validar.py',46),
  ('expression -> expression AND term','expression',3,'p_expression','validar.py',47),
  ('expression -> expression OR term','expression',3,'p_expression','validar.py',48),
  ('expression -> term','expression',1,'p_expression','validar.py',49),
  ('term -> term TIMES factor','term',3,'p_term','validar.py',55),
  ('term -> term DIVIDE factor','term',3,'p_term','validar.py',56),
  ('term -> NOT factor','term',2,'p_term','validar.py',57),
  ('term -> factor','term',1,'p_term','validar.py',58),
  ('factor -> NUMBER','factor',1,'p_factor','validar.py',64),
  ('factor -> BOOLEAN','factor',1,'p_factor','validar.py',65),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','validar.py',66),
]
